#!/usr/bin/env python3
# MobileGL - dispatcher/gen_forwarders.py
# mg-3backends: generates forwarding shims so the unified entry library
# (libmobileglues.so) can route every GL/EGL symbol the launcher resolves by
# dlsym to the active backend core (MobileGL DirectVulkan/DirectGLES, or the
# vendored MobileGlues GLES core).
#
# Parses the Khronos headers vendored in this repository and emits one lazy
# forwarder per function prototype. Functions the core does not export fall
# back to the core's own eglGetProcAddress at bind time (see dispatcher.c).
#
# SPDX-License-Identifier: LGPL-3.0-only

import argparse
import re
import sys

PROTO_RE = re.compile(
    r"\b(?:GLAPI|EGLAPI)\s+"
    r"([^;()]+?)"                   # return type: no ';'/parens so a match can never span prototypes
    r"\s*(?:APIENTRY|GLAPIENTRY|EGLAPIENTRY)\s+"
    r"(gl[A-Za-z0-9_]+|egl[A-Za-z0-9_]+)\s*"
    r"\(([^()]*)\)\s*;",           # params (no nested parens allowed)
    re.S,
)

SKIP_NAMES = {
    # Dispatcher implements this itself (smart forward, see dispatcher.c).
    "eglGetProcAddress",
}

NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    text = re.sub(r"//[^\n]*", " ", text)
    return text


def split_top_level(s: str):
    parts, depth, cur = [], 0, []
    for ch in s:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(cur))
            cur = []
        else:
            cur.append(ch)
    tail = "".join(cur).strip()
    if tail:
        parts.append(tail)
    return parts


def param_name(p: str):
    p = p.strip()
    if p in ("", "void"):
        return None
    # "GLuint foo[4]" style arrays -> normalize to pointer
    p = re.sub(r"\[[^\]]*\]", " ", p)
    toks = p.replace("*", " * ").split()
    if not toks:
        return None
    name = toks[-1].strip()
    if name == "*":
        return None
    if not NAME_RE.match(name):
        return None
    # A trailing token that is actually a type keyword means the param is
    # unnamed (should not happen in Khronos headers, but be defensive).
    if name in ("const", "volatile", "struct", "unsigned", "signed", "long", "short"):
        return None
    return name


def is_void_ret(ret: str) -> bool:
    return ret.strip() == "void"


def parse_headers(paths):
    funcs = {}    # name -> (ret, params_text, args, source)
    skipped = []  # (name, reason)
    for path in paths:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            text = strip_comments(f.read())
        for m in PROTO_RE.finditer(text):
            ret, name, params = m.group(1).strip(), m.group(2), m.group(3).strip()
            if name in SKIP_NAMES:
                continue
            if name in funcs:
                continue
            if "..." in params:
                skipped.append((name, "varargs"))
                continue
            plist = split_top_level(params)
            if params == "" or (len(plist) == 1 and plist[0].strip() == "void"):
                args, ptext = "", "void"
            else:
                names = []
                ok = True
                for p in plist:
                    n = param_name(p)
                    if n is None:
                        ok = False
                        break
                    names.append(n)
                if not ok:
                    skipped.append((name, "unnamed-or-complex-params"))
                    continue
                ptext = ", ".join(x.strip() for x in plist)
                args = ", ".join(names)
            funcs[name] = (ret, ptext, args, path)
    return funcs, skipped


def emit(funcs, out_path):
    lines = []
    a = lines.append
    a("/* MobileGL - dispatcher/forwarders.c (GENERATED by gen_forwarders.py)")
    a(" * mg-3backends: one lazy forwarder per GL/EGL prototype found in the")
    a(" * vendored Khronos headers. Do not edit; regenerate instead.")
    a(" * SPDX-License-Identifier: LGPL-3.0-only */")
    a("")
    a("#define GL_GLEXT_PROTOTYPES 1")
    a("#define EGL_EGLEXT_PROTOTYPES 1")
    a("#include <stddef.h>")
    a("#include <GL/glcorearb.h>")
    a("#include <GL/glext.h>")
    a("#include <EGL/egl.h>")
    a("#include <EGL/eglext.h>")
    a('#include "dispatcher.h"')
    a("")
    # Group per source header for readable diffs.
    by_src = {}
    for name, (ret, ptext, args, src) in funcs.items():
        by_src.setdefault(src, []).append(name)
    for src, names in sorted(by_src.items()):
        a("/* ===== %s (%d functions) ===== */" % (src, len(names)))
        for name in sorted(names):
            ret, ptext, args, _ = funcs[name]
            a("static %s (*mg_p_%s)(%s) = NULL;" % (ret, name, ptext))
        a("")
        for name in sorted(names):
            ret, ptext, args, _ = funcs[name]
            a("__attribute__((visibility(\"default\"))) %s %s(%s) {" % (ret, name, ptext))
            a("    MG_BIND(mg_p_%s, \"%s\");" % (name, name))
            a("    if (mg_p_%s) {" % name)
            if is_void_ret(ret):
                a("        mg_p_%s(%s);" % (name, args))
                a("        return;")
            else:
                a("        return mg_p_%s(%s);" % (name, args))
            a("    }")
            if not is_void_ret(ret):
                a("    return (%s)0;" % ret)
            a("}")
        a("")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--gl-header", action="append", default=[])
    ap.add_argument("--egl-header", action="append", default=[])
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    headers = list(args.gl_header) + list(args.egl_header)
    funcs, skipped = parse_headers(headers)
    emit(funcs, args.out)

    sys.stderr.write("[gen_forwarders] emitted %d forwarders -> %s\n" % (len(funcs), args.out))
    if skipped:
        sys.stderr.write("[gen_forwarders] skipped %d: %s\n" % (
            len(skipped), ", ".join("%s(%s)" % s for s in skipped[:24])))
    # Varargs prototypes must stay zero for full dlsym coverage.
    hard = [s for s in skipped if s[1] != "unnamed-or-complex-params"]
    if hard:
        sys.exit("FATAL: unforwardable prototypes present: %s" % hard)


if __name__ == "__main__":
    main()
